# Generated by Django 3.0.7 on 2020-06-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('titulo', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('markup', models.TextField()),
                ('tags', models.TextField(default='')),
            ],
        ),
    ]
